### ISSUE TITLE
Collect data from Launcher and Deploy

### ISSUE THREAD

**Issue by brunoamuniz** [TotalCross/totalcross-vscode-plugin#2]
Hey guys,

We need to collect some data of ppl using the Launcher and Deploy classes, like date of usage.
Send this info to firebase, ok?

This stats are important to know if ppl are using totalcross or not =)

Cheers,

**Comment by ItaloYeltsin** [comment]
For now, I would implement an endpoint in the totalcross-user-area project that allows to register the date, the user and which method the user is using (deploy, package, launcher). Both, this plugin and cls must send these info to the server in an independent thread in order to not annoy the user when she/he is without internet connection.

**Comment by ItaloYeltsin** [comment]
We have to show a use term explaining that we get these parameters for a matter of statistics of user, not to send their information to other companies. Please, someone contact a lawyer to write this term

**Comment by ItaloYeltsin** [comment]
this is made by the own sdk! We've already implemented the feature to ask if the user would like to contribute [6ce95f](https://github.com/TotalCross/totalcross-vscode-plugin/commit/6ce95f72102443b7b263a8dcb34ca11d85397089)
